### ISSUE TITLE
Stern seems to not follow logs of new containers on restart

### ISSUE THREAD

**Issue by valer-cara** [wercker/stern#70]
### What

Stern does not print logs from restarted containers. If I re-run stern after a container failure/restart, the new container's logs are printed.

### Reproduce

Create the following failing pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo

spec:
  containers:
    - name: foo
      image: busybox
      command: ["sh", "-c", "touch /log; tail -f /log"]
      readinessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 5
        exec:
          command: ["sh", "-c", "echo $(date) ::: Readiness probe >> /log; grep imready /foo"]

      livenessProbe:
        initialDelaySeconds: 5
        timeoutSeconds: 5
        exec:
          command: ["sh", "-c", "echo $(date) ::: Liveness probe >> /log; grep imalive /foo"]
```

Check logs:
```
stern foo
```

**Comment by prune998** [comment]
I can confirm this behaviour
Have no time right now to try to debug it, help would be welcomed as in some of my `pods` with multiple containers, one container sometimes fail/restart while the other is still working.
This leads to to `stern` stopping to send logs for the restarted container.

FYI, application container is restarting as it does not have network setup, because Istio Sidecar is too long to initiate.

**Comment by max-zelinski** [comment]
same problem here

**Comment by majelbstoat** [comment]
This issue also affects us quite a lot. Not being certain that logs are displayed under some circumstances after restarts causes us to have to restart stern regularly. I've definitely burned time trying to figure out a bug only to find that stern just wasn't logging the output.

Given that @markxnelson mentioned in https://github.com/wercker/stern/issues/71 that stern is still maintained, and that they're working through the backlog, wanted to bump this a little.

**Comment by prune998** [comment]
bumping too !

**Comment by sstarcher** [comment]
this would be very helpful

**Comment by nichzl** [comment]
Still not working (1.10.0).

**Comment by grosser** [comment]
Fixed here https://github.com/grosser/stern/pull/2
released as https://github.com/grosser/stern/releases/tag/1.12.1 (with a few other fixed)

**Comment by valer-cara** [comment]
Awsome! Thanks @grosser :partying_face: Closing this issue

**Comment by grosser** [comment]
it's a fork, so plz don't close the issue :D

**Comment by valer-cara** [comment]
you're right :joy: my bad. reopening

**Comment by rocketraman** [comment]
@grosser I'm using your fork version 1.12.1 and still encountered this issue.

**Comment by grosser** [comment]
damn ... seemed to work for me, maybe just a few edge-cases got fixed, plz open a PR if you find the bug
might be time to find a better maintained tool :(
